spring:
  redis:
    # redis?????(???0)????????3???????????????
    database: 0
    # redis?????????loaclhost?
    host: 127.0.0.1
    # redis??????6379?
    post: 6379
    # redis??????????
    password:
    # redis????????????
    timeout: 5000
    lettuce:
      pool:
        max-active: 1000  #????????????????????
        max-idle: 6   #????????
        min-idle: 2   #????????
        max-wait: 1000 #???????????(??????????)
      shutdown-timeout: 100 #??????
